### ISSUE TITLE
Simulating a placeholder break the mention plugin

### ISSUE THREAD

**Issue by nferruzzi** [linkedin/Hakawai#17]
Hello,

on my text view I set a fake placeholder text that I need to remove before editing starts. To accomplish this I've some logic to eventually set the textView text to @""  on my delegate textViewDidBeginEditing. Unfortunately in this case I can't create a mention anymore at location 0 by pressing control characters; mention creating can be resumed by writing/deleting some text and then it works at location 0 too. 
Looking at the code when my user tap the text view I still have my fake "placeholder text" and the internal state is set at "Stalled" because it believes I'm tapping in a middle of a world.

It would be great if you could add support for a placeholder :) meanwhile could you have a look at this problem ?

thanks in advance

**Comment by nferruzzi** [comment]
its a bit hacky, because it relies on implementation details but I can work around this problem by forcing the plugin state machine 

[self.texView setText:@""];
[self.plugin.startDetectionStateMachine setState:0];

also works with 

[self.textView removeTextForRange:NSMakeRange(0, self.textView.length)];

ty

**Comment by dotjim** [comment]
I can confirm this issue.  Programatically adjusting the UITextView with e.g. `setText:` or `setAttributedText:` in any fashion (with nil, an empty string, or otherwise) will visibly update the contents of the UITextView, however the Hakawai state machine does not update and retains it's former view of the UITextView's string buffer.

An example is to have a UITextView with the current contents of "Test".  Calling `[textView setText:@""]` and then typing "Test" would result in the Hakawai state machine's string buffer holding "TestTest" rather than "Test" as it should.

There appears to be no external Hakawai API to remedy this, and both suggested workarounds above are insufficient/inappropriate.  The category helper `removeTextForRange:` approach does not adjust the state machines view of the string buffer, and `[self.plugin.startDetectionStateMachine setState:0];` (whilst also an internal API) does not handle situations where e.g. mention creation is in mid process.

I have submitted the above pull request as one possible solution.  This introduces the `textViewDidProgrammaticallyUpdate` concept elsewhere within this module to the HKWTextView class itself, allowing associated plugins to update their state accordingly.

**Comment by dotjim** [comment]
@nferruzzi #19 has been merged so you can now call `textViewDidProgrammaticallyUpdate` on the HKWTextView after programatic updates via e.g. `setText:` or `setAttributedText:` ensuring any attached plugins update their state accordingly.

This issue should be good to close now.

**Comment by austinzheng** [comment]
Please re-open if you need any follow-up support.
