### ISSUE TITLE
Cursor stops when deleting text while using Mentions plugin

### ISSUE THREAD

**Issue by mrsmiley009** [linkedin/Hakawai#4]
This bug can be verified in the LinkedIn app's new post view:

1) type a somewhat long message into the textview 
2) hold down the delete button

Observe behavior that after deleting some text the cursor will get stuck and stop deleting characters until you let off the button and re-press.  I suspect this has something to do with the code that deals with partially deleting names of Mentions, e.g. turning "Ryan Downing" into "Ryan", but I haven't investigated further.  Happy to provide more info if needed / take a look with you.

**Comment by austinzheng** [comment]
I found the problem. It's due to the fact that we have code which disables the predictive suggestions if the selection range is changed such that it touches a mention. (This was to fix a bug where you could autocorrect text including a mention into something else, mangling the mention, and the state machine couldn't reliably pick up on this.) However, the way fast delete works is that it selects part of the text and then deletes it, which causes that code to trigger.

The code that enables or disables the predictive suggestions stops editing, changes the autocorrect setting, and restarts editing (since the autocorrect setting can't be changed while the text view is the first responder). However, doing so interrupts the user's delete (or select) operation.

As well, there was a bug in the aforementioned code which toggled the autocorrect mode even if the selection wasn't touching any mentions. I've fixed that. The updated version of the code will allow users to fast delete when there are no mentions, but will stop fast deletion when they reach a mention. (It retains the current text selection behavior, in which the user must tap again on the selection bars in order to continue selecting text if they move the selection range into a mention.)
