### ISSUE TITLE
Mentions plugin : HKWRoundedRectBackgroundAttributeName broken in swift

### ISSUE THREAD

**Issue by vergilw** [linkedin/Hakawai#75]
1. HKWRoundedRectBackgroundAttributeName not work in swift when i manual set this attribute
```
unselectedMentionAttributes: [NSAttributedStringKey.font: UIFont.systemFont(ofSize: 14),
                             NSAttributedStringKey.foregroundColor: UIColor.black,
                             HKWRoundedRectBackgroundAttributeName: HKWRoundedRectBackgroundAttributeValue.init(backgroundColor: UIColor("#f2faff"))],
selectedMentionAttributes: [NSAttributedStringKey.font: UIFont.systemFont(ofSize: 14),
                           NSAttributedStringKey.foregroundColor: UIColor.white,
                           HKWRoundedRectBackgroundAttributeName: HKWRoundedRectBackgroundAttributeValue.init(backgroundColor: UIColor("#718dff"))])
```

2. mention backgroundColor height not correct when i select mention (cause of set selected metion attributes font size less than textview size)

and i hope can support mention attribute inset control

**Comment by SergeyAniskin** [comment]
Hi! Unfortunately this wouldn't work anymore until proper comparison implemented in HKWLayoutManager:roundedRectBackgroundAttributeTuplesInTextStorage. Comparison if (attr == HKWRoundedRectBackgroundAttributeName) {} doesn't work because application and library has own copy of static variable HKWRoundedRectBackgroundAttributeName so comparison would always fail. You have to use mentioned below function to create plugin - this would guarantee that the same instance of HKWRoundedRectBackgroundAttributeName is used

 + (instancetype)mentionsPluginWithChooserMode:(HKWMentionsChooserPositionMode)mode
                            controlCharacters:(NSCharacterSet *)controlCharacterSet
                                 searchLength:(NSInteger)searchLength
                              unselectedColor:(UIColor *)unselectedColor
                                selectedColor:(UIColor *)selectedColor
                      selectedBackgroundColor:(UIColor *)selectedBackgroundColor;

**Comment by dgattey** [comment]
@SergeyAniskin sorry - not familiar with the internals here. Are you saying that changing the `attr == HKWRoundedRectBackgroundAttributeName` to a `isEqualToString` check would fix this in the LayoutManager? Or are you saying that it's not going to work because the name won't be equal?

Is there a sample project/diff I could test a fix against?

**Comment by dgattey** [comment]
@vergilw does the linked PR fix your issue?

**Comment by SergeyAniskin** [comment]
> HKWRoundedRectBackgroundAttributeName

Yep, isEqualToString would solve this issue

**Comment by dgattey** [comment]
Awesome, I'll merge it - thank you!

**Comment by SergeyAniskin** [comment]
> Awesome, I'll merge it - thank you!

other solution could be I think to remove static and expose constant via "extern", so compiler wouldn't create several copies of static variable for each module and would just use linker to resolver extern. This would be better optimized solution

**Comment by dgattey** [comment]
Not familiar with extern - I'll look into that, thanks

**Comment by SergeyAniskin** [comment]
> Not familiar with extern - I'll look into that, thanks
extern or OBJC_EXTERN ...

In HKWCustomAttributes.h file:
OBJC_EXTERN NSString* _Nonnull const HKWRoundedRectBackgroundAttributeName;

In HKWCustomAttributes.m file (create one): 
NSString* _Nonnull const HKWRoundedRectBackgroundAttributeName = @"HKWRoundedRectBackgroundAttributeName";

In 'm' file compiler would create physical variable, in 'h' file you just expose to anyone that it exists and at later stages linker would replace its address with proper one.

**Comment by dgattey** [comment]
Thanks for the help! I've improved it based on the above in the referenced PR
