### ISSUE TITLE
Unable to change height constraint of custom chooser view

### ISSUE THREAD

**Issue by erikackermann** [linkedin/Hakawai#8]
I am setting up my custom chooser view with the following constraints like so:
```objc
UIView *keyboardToolbar = [[UIView alloc] initWithFrame:CGRectMake(0, 0, self.frame.size.width, 50)];
keyboardToolbar.translatesAutoresizingMaskIntoConstraints = NO;

[_mentionsPlugin setChooserTopLevelView:keyboardToolbar attachmentBlock:^(UIView *view) {
    [keyboardToolbar addConstraint:[NSLayoutConstraint constraintWithItem:view
                                                                attribute:NSLayoutAttributeHeight
                                                                relatedBy:NSLayoutRelationEqual
                                                                   toItem:keyboardToolbar
                                                                attribute:NSLayoutAttributeHeight
                                                               multiplier:1.0
                                                                 constant:0.0]];
}];

textView.inputAccessoryView = keyboardToolbar;
```

When the `keyboardToolbar` is initialized, it has the frame {0, 0, 375, 50} on an iPhone 6.  After the setup block is called, I get this error:

```
Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x7fae93f30b10 V:[UIView:0x7fae93cab380(50)]>",
    "<NSLayoutConstraint:0x7fae93f140d0 HTUserMentionChooserView:0x7fae93abef40.height == UIView:0x7fae93cab380.height>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fae93f09bd0 h=--& v=--& V:[HTUserMentionChooserView:0x7fae93abef40(100)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fae93f140d0 HTUserMentionChooserView:0x7fae93abef40.height == UIView:0x7fae93cab380.height>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

**Comment by austinzheng** [comment]
A few quick questions while I try to get down to the bottom of this:

* I assume you aren't constraining your view's height to be explicitly 100.
* Are you laying out your ChooserView in a XIB?
* What happens if you set `self.translatesAutoresizingMaskIntoConstraints = NO;` in your chooser view's`awakeFromNib` method?
* If that doesn't work, can you try setting the view's `autoresizingMask` to None?

I have to run now but I'll look at this more closely later.

(After we get down to the bottom of this I will be updating the documentation with best practices.)

**Comment by erikackermann** [comment]
Yes, I am not setting a height constraint on the chooser view or the top level view.  And I don't set a size on the chooser view; the frame is being set by the mentions state machine when it creates the custom chooser view.

I am not laying out the custom chooser in a .xib.  It is all done programmatically.  I am setting translatesAutoresizingMaskIntoConstraints to NO but this doesn't solve it.

I'll try your suggestion about setting the auto resizing mask to none and report back.  Thanks.

**Comment by austinzheng** [comment]
This isn't a solution, but I just remembered that the placeholder frame the chooser view is constructed with (before it gets constrained) has a height of 100. (`HKWMentionsCreationStateMachine.m`; line 520.) Wanted to make a note before I forgot.

**Comment by austinzheng** [comment]
Another thing I've found when creating views in code (for other projects) is that I've had to set the `translatesAutoresizingMaskIntoConstraints` property for all subviews to `NO` when I create/set up the view, otherwise the view doesn't play well with Auto Layout. (I haven't had this issue with views described by XIBs.) This is true for both the default chooser and the text view (both of which are implemented in code).

**Comment by erikackermann** [comment]
Yes, this is where the chooser view's frame is initially set:
https://github.com/linkedin/Hakawai/blob/master/Hakawai/Mentions/HKWMentionsCreationStateMachine.m#L520

But (from the comment above that line), this frame is meant to be temporary until constraints are added.  I bet something is implicitly creating constraints from this frame.  I couldn't figure where these extra constraints were being set, but they are not present when this block is called: https://github.com/linkedin/Hakawai/blob/master/Hakawai/Core/HKWTextView%2BPlugins.m#L201
so they must be added after.

**Comment by austinzheng** [comment]
I found a bug in HWKTextView's initializer when the text view is being initialized programmatically (as opposed to from a XIB). I bring it up because the issue in question was whether or not the text container was tracking the height of the text view, which may or may not be related to your issue. Will push a fix soon.

In the meantime, I've made a new project and am trying to replicate your setup. Stay tuned...

**Comment by austinzheng** [comment]
Let me know if any of the way too many suggestions I gave you last week helped. Otherwise, I'm still working on replicating your setup...

**Comment by erikackermann** [comment]
I've made sure I'm setting `translatesAutoresizingMaskIntoConstraints` to `NO` everywhere; still not fixing it.

I'm guessing that the dummy frame set initially (where the 100 height gets set) is being translated into constraints somewhere (accidentally)?

**Comment by austinzheng** [comment]
I'll check again for constraints being created or set.

One final quick thing to do: could you instantiate your chooser view by itself, and add the same constraints to an accessory view on a normal text view? If we can isolate the chooser view from the rest of Hakawai, we can get a clearer sense of where the root cause lies.

Alternately, let me know if you'd be willing to send me some of the code that's giving you trouble. (I completely understand if you're not comfortable or the code is sensitive.) If we go this route it'll probably be quicker for me and more convenient for you.

**Comment by erikackermann** [comment]
Hey @austinzheng.  I tried using my custom chooser view as an accessory view for a a normal text view; no issues there.

I'm also trying to figure out how I can easily send you some code... my project is rather large and I'm not sure what single file or snippet could be useful to send.

**Comment by erikackermann** [comment]
Ah, I was forgetting to set `translatesAutoresizingMaskIntoConstraints` to NO in one place!  Apologies!

This issue was cause by code on my side; we can close this.

**Comment by austinzheng** [comment]
:+1: 

If you run into any more issues, open more tickets!
